### ISSUE TITLE
Interstitial Error Occurred Event?

### ISSUE THREAD

**Issue by Linder-Boss** [AdsJumbo/AdsJumbo.com#2]
It would be nice to have an event OnErrorOccurred event.

**Comment by AdsJumbo** [comment]
Hi,

UPDATE: OnAdError event for the interstitial and banner ad was added, Please update NuGet to version AdsJumbo - 5.5.9.

Just call:

InterstitialAd.OnAdError += InterstitialAd_OnAdError;
BannerAd.OnAdError += BannerAd_OnAdError;
Handle:

private void BannerAd_OnAdError(object sender, RoutedEventArgs e)
{
  // When Error Occurred on Banner Ad
}
Otherwise you can reach us at mail: info@adsjumbo.com
If you want to activate your app/game just hit the button "Request Activation" this push all premium campaigns and demand.

Any feedback is welcome!

Regards,
AdsJumbo.com Team
