### ISSUE TITLE
[Ad Formats] How to create Native Ads - component-based ads for UWP?

### ISSUE THREAD

**Issue by Delaire** [AdsJumbo/AdsJumbo.com#23]
Hello I am not seeing any examples on how to create component-based ads?

**Comment by adjumbo** [comment]
Hello, Thanks for your feedback. Our ad platform currently supports C sharp, C++, WinJS and WPF implementation with options of banner and interstitial ads. Component-based ads arent available currently due to low interest of our advertisers.
For more info, please reach us via mail.
Best Regards, AdsJumbo.com Team

**Comment by Delaire** [comment]
Hello in that case you should update you description page as it states that you can add native ads to apps:
![image](https://user-images.githubusercontent.com/6408479/110294886-b924b000-7ff0-11eb-9788-138cec3e0339.png)
