### ISSUE TITLE
Failed Windows App Certification Kit when submit to Windows Store

### ISSUE THREAD

**Issue by alexvl1510** [AdsJumbo/AdsJumbo.com#4]
I use Windows App Certification Kit to launch test my app after the integration is completed. But the certification failed as below:

> General metadata correctness
> Error Found: The general metadata correctness test detected the following errors:
> **The assembly AdsJumbo in file AdsJumbo.winmd has a non-empty manifest resources table. Every Windows Runtime assembly must have an empty manifest resources table.**
> Impact if not fixed: Microsoft store doesn't allow apps that don't pass Windows Runtime Metadata Validation.
> How to fix: Please ensure that the compiler you are using to generate your Windows Runtime types is up to date with with the Windows Runtime specifications.

I already submit that package to store and still received the failure above.

Please fix sdk (AdsJumbo.winmd). Thanks

**Comment by adjumbo** [comment]
Hello,

This can be caused by your project, if is in C++, our SDK so far works perfectly on C# / XAML projects. Please check the latest release NuGet package, there was removed all static resources which can invoke this error or issue.

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team

**Comment by RickKeeney** [comment]
I am seeing this issue with AdJumbo 5.9.1 when I submitted my app to the store just now:

FAILED
General metadata correctness
Error Found: The general metadata correctness test detected the following errors:
The assembly AdsJumbo in file AdsJumbo.winmd has a non-empty manifest resources table. Every Windows Runtime assembly must have an empty manifest resources table.

In an answer above, the AdsJumbo team indicates this is fixed in their assembly, but can be caused by the project.  More details would be helpful.
